version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/continuous-delivery-blog
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: |
          echo Running dependency-check
          npm run dependency-check
          echo Running Security Static Analysis
          npm run sec-static-analysis
          echo Running unit tests
          yarn test
  deploy:
    machine:
        enabled: true
    working_directory: ~/continuous-delivery-blog
    steps:
      - checkout
      - run: bash .circleci/setup-heroku.sh
      - run:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
            git push heroku master
            heroku restart
            fi
workflows:
  version: 2
  pipeline:
    jobs:
      - build
      - deploy:
        requires:
          - build
